# FROM node:22.13.1-bookworm
FROM node:21.7.3-bookworm
# FROM node:21.7.3-bookworm
# FROM node:21.7.3-alpine3.20

ENV PROJECT /frontend

WORKDIR ${PROJECT}



COPY .${PROJECT} ${PROJECT}

RUN npm cache verify

RUN npm install



RUN npm run build
CMD ["npm", "run", "start"]